"""database initialization

Revision ID: 78cd9abc9185
Revises: 
Create Date: 2019-08-28 23:17:51.966384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78cd9abc9185'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_number', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_email'), 'student', ['email'], unique=True)
    op.create_index(op.f('ix_student_student_number'), 'student', ['student_number'], unique=True)
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_number', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_email'), 'teacher', ['email'], unique=True)
    op.create_index(op.f('ix_teacher_teacher_number'), 'teacher', ['teacher_number'], unique=True)
    op.create_table('unit',
    sa.Column('unit_id', sa.String(length=20), nullable=False),
    sa.Column('unit_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_table('association_student_unit',
    sa.Column('Student', sa.Integer(), nullable=True),
    sa.Column('Unit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Student'], ['student.id'], ),
    sa.ForeignKeyConstraint(['Unit'], ['unit.unit_id'], )
    )
    op.create_table('association_teacher_unit',
    sa.Column('Teacher', sa.Integer(), nullable=True),
    sa.Column('Unit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Teacher'], ['teacher.id'], ),
    sa.ForeignKeyConstraint(['Unit'], ['unit.unit_id'], )
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('due_time', sa.DateTime(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.unit_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('mark', sa.Float(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_url'), 'record', ['url'], unique=True)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_index(op.f('ix_record_url'), table_name='record')
    op.drop_table('record')
    op.drop_table('task')
    op.drop_table('association_teacher_unit')
    op.drop_table('association_student_unit')
    op.drop_table('unit')
    op.drop_index(op.f('ix_teacher_teacher_number'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_email'), table_name='teacher')
    op.drop_table('teacher')
    op.drop_index(op.f('ix_student_student_number'), table_name='student')
    op.drop_index(op.f('ix_student_email'), table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###
